= Paneron extension kit

The kit currently contains a set of Paneron types relevant for extension development.

== Extension development

Paneron extensions are written in TypeScript based on React, and can make use of Blueprint 3 UI components.

An extension is essentially a React component that is given as props
some functions that simplify interaction with underlying data repository.

[NOTE]
====
These guidelines are for Paneron 1.0.0-alpha17. Before that version the process was slightly different.
Specifying PANERON_PLUGIN_DIR environment variable is no longer suggested.
====

=== Setup using GitHub as repository host

. Think of an ID for your extension (e.g., my-extension).

. On GitHub, create a new repository using Paneron extension template repository (https://github.com/paneron/extension-template-basic).

. Clone the repository you’ve created and edit package.json to fill in your extension name, description, and author (see placeholders).

. Inside Paneron app data directory, create subdirectory chain 'plugins/@riboseinc/paneron-extension-my-extension'.
+
That is where Paneron will expect your extension built form to reside.

. For testing purposes, obtain Paneron source code (clone https://github.com/paneron/paneron) and build the project locally.

==== Iteration

After you make changes:

. Rebuild your extension from its repository root:
+
[source,sh]
--
$ yarn build
--

. Copy the _contents_ of `dist/` into Paneron’s built extension directory you created during preliminary setup.

. Launch your local build of Paneron using a command like this, from within Paneron repository root:
+
[source,sh]
--
$ env PANERON_DEV_PLUGIN=my-extension yarn dev
--

==== Release

An extension must be released as a separate NPM package, specifying entry as `plugin.js`
(see the template extension for example packaging).

When ready & tested, release your extension on NPM
by running this command from within `dist/` subdirectory
in your extension repository:

[source,sh]
--
$ npm publish --access public
--

NOTE: `--access public` is only necessary first time you publish the extension. (See [NPM CLI docs](https://docs.npmjs.com/creating-and-publishing-scoped-public-packages#publishing-scoped-public-packages).)

NOTE: Currently, only extensions released under `@riboseinc` NPM scope are supported.
Plugin name must be prefixed with `paneron-extension-` (e.g., `@riboseinc/paneron-extension-my-extension`).

To test your extension after it’s released, run Paneron as a regular user would,
without PANERON_DEV_PLUGIN variable.

=== Rules of Paneron extensions

There are some extra constraints placed upon extension component code, mostly due to limitations
of extension mechanism at this point in time.

. An extension must not have any dependencies specified in package.json.
  Anything you want to import should be provided by Paneron (see below what is).
  (You can use devDependencies, though.)

. An extension cannot call browser window’s native functions.
  If you need `setTimeout()`, use `setTimeout` prop passed to your top-level extension component.
  Using `Blob` or `addEventListener()` is not possible currently.
+
If this rule is not observed, you may end up getting a confusing blank screen
after opening a repository using your extension and “DevTools was disconnected from the page” in console.

==== Modules you can import

Here are the modules you can import:

* "react"
* "react-window"
* "@emotion/core"
* "@emotion/styled"
* "emotion"
* "@riboseinc/paneron-extension-kit"
* "@riboseinc/paneron-registry-kit"
* "@blueprintjs/core"
* "@blueprintjs/datetime"
* "@blueprintjs/icons"
* "@blueprintjs/select"
* "electron-log"
* "js-yaml"
* "throttle-debounce"

Again, you must not have anything in your dependencies,
but you may want to add what you use from the above to your _devDependencies_
for TypeScript development convenience.

=== Using Emotion for styling components

Here’s how a simple component can be written using Emotion:

[source,tsx]
--
/** @jsx jsx */

import React, { useState } from 'react';
import { css, jsx } from '@emotion/core';

const MyRepositoryView: React.FC<RepositoryViewProps> = function (props) {
  const [value, setValue] = useState(null);
  return <div css={css`padding: 1rem;`}>Welcome to repository {props.title}!</div>;
};
--

[NOTE]
====
If using React fragment shorthand syntax (`<>…</>`),
keep the React import and add `@jsxFrag` pragma:

[source,tsx]
--
/** @jsx jsx */
/** @jsxFrag React.Fragment */

import React, { useState } from 'react';
import { css, jsx } from '@emotion/core';

const MyRepositoryView: React.FC<RepositoryViewProps> = function (props) {
  const [value, setValue] = useState(null);
  return <>
    <div css={css`padding: 1rem;`}>Welcome to repository {props.title}!</div>
  </>;
};
--
====
