= Paneron extension kit

The kit currently contains a set of Paneron types relevant for extension development.

== Extension development

Paneron extensions are written in TypeScript based on React, and can make use of Blueprint 3 UI components.

An extension is essentially a React component that is given as props
some functions that simplify interaction with underlying data repository.

=== Setup

. Create a new repository using Paneron extension template repository (https://github.com/paneron/extension-template-basic).

. For testing purposes, obtain Paneron source code (clone https://github.com/paneron/paneron) and build the project locally.

. Create a directory named `paneron-extension-dev` somewhere on your machine.

==== Iteration

After you make changes:

. Rebuild your extension from its repository root:
+
[source,sh]
--
$ yarn build
--

. Copy the _contents_ of `dist/` into `paneron-extension-dev/@riboseinc/paneron-extension-<your-extension-name>`.

. Launch your local build of Paneron using a command like this, from within Paneron repository root:
+
[source,sh]
--
$ env PANERON_PLUGIN_DIR=/path/to/your/paneron-extension-dev/directory yarn dev
--

==== Release

An extension must be released as a separate NPM package, specifying entry as `plugin.js`
(see template extension for example packaging).

When ready & tested, release your extension on NPM:

[source,sh]
--
$ npm publish
--

NOTE: Currently, only extensions released under `@riboseinc` NPM scope are supported.
Plugin name must be prefixed with `paneron-extension-` (e.g., `@riboseinc/paneron-extension-foo-registry`).

=== Rules of Paneron extensions

There are some extra constraints placed upon extension component code, mostly due to limitations
of extension mechanism at this point in time.

. An extension must not have any dependencies specified in package.json.
  Anything you want to import should be provided by Paneron (see below what is).
  (You can use devDependencies, though.)

. An extension cannot call browser window’s native functions.
  If you need `setTimeout()`, use `setTimeout` prop passed to your top-level extension component.
  Using `Blob` or `addEventListener()` is not possible currently.
+
If this rule is not observed, you may end up getting a confusing blank screen
after opening a repository using your extension and “DevTools was disconnected from the page” in console.

==== Modules you can import

Here are the modules you can import:

* "react"
* "react-window"
* "@emotion/core"
* "@emotion/styled"
* "emotion"
* "@riboseinc/paneron-extension-kit"
* "@riboseinc/paneron-registry-kit"
* "@blueprintjs/core"
* "@blueprintjs/datetime"
* "@blueprintjs/icons"
* "@blueprintjs/select"
* "electron-log"
* "js-yaml"
* "throttle-debounce"

Again, you must not have anything in your dependencies,
but you may want to add what you use from the above to your _devDependencies_
for TypeScript development convenience.

=== Using Emotion for styling components

Here’s how a simple component can be written using Emotion:

[source,tsx]
--
/** @jsx jsx */

import React, { useState } from 'react';
import { css, jsx } from '@emotion/core';

const MyRepositoryView: React.FC<RepositoryViewProps> = function (props) {
  const [value, setValue] = useState(null);
  return <div css={css`padding: 1rem;`}>Welcome to repository {props.title}!</div>;
};
--

[NOTE]
====
If using React fragment shorthand syntax (`<>…</>`),
keep the React import and add `@jsxFrag` pragma:

[source,tsx]
--
/** @jsx jsx */
/** @jsxFrag React.Fragment */

import React, { useState } from 'react';
import { css, jsx } from '@emotion/core';

const MyRepositoryView: React.FC<RepositoryViewProps> = function (props) {
  const [value, setValue] = useState(null);
  return <>
    <div css={css`padding: 1rem;`}>Welcome to repository {props.title}!</div>
  </>;
};
--
====
