= Paneron extension kit

== Extension development

NOTE: Currently, only extensions released under `@riboseinc` NPM scope are supported.
Plugin name must be prefixed with `paneron-extension-` (e.g., `@riboseinc/paneron-extension-foo-registry`).

=== Setup

. Create a new repository using Paneron extension template repository (link to be added).

. Clone Paneron repository (link to be added) and build Paneron locally.

. Create a directory named `paneron-extension-dev` somewhere on your machine.

==== Iteration

After you make changes:

. Rebuild the extension from repository root:
+
[source,sh]
--
$ yarn build
--

. Copy the _contents_ of `dist/` into `paneron-extension-dev/@riboseinc/paneron-extension-<your-extension-name>`.

. Launch your local build of Paneron using a command like this:
+
[source,sh]
--
$ env PANERON_PLUGIN_DIR=/path/to/your/paneron-extension-dev/directory yarn dev
--

==== Release

When ready, release NPM package and test on production Paneron build.

=== Rules of Paneron extensions

==== Depending on other modules

An extension should not have any dependencies specified in package.json.
Anything you want to import should be provided by Paneron.

Here are modules you can import:

* "@blueprintjs/core"
* "@blueprintjs/datetime"
* "@blueprintjs/icons"
* "@blueprintjs/select"
* "@emotion/core"
* "@riboseinc/paneron-extension-kit"
* "@riboseinc/paneron-registry-kit"
* "electron-log"
* "js-yaml"
* "react-window"
* "throttle-debounce"

==== Using React

An extension cannot import React directly. Due to how resolving extensions at runtime works currently,
importing React in your components will cause two React instances to be running, which will break hooks.

Instead, your components will be passed a `react` prop.
Use that prop to invoke hooks and use fragments.

For example:

[source,tsx]
--
const MyRepositoryView: React.FC<RepositoryViewProps> = function ({ react, title }) {
  const [value, setValue] = react.useState(null);
  return <react.Fragment>Welcome to repository {title}!</react.Fragment>
}

This may change in future.
