= Paneron extension kit

The kit currently contains a set of types relevant for Paneron extension development,
a helper function `exposePlugin()`, and a couple of UI widgets.

== Extension development

Paneron extensions are written in TypeScript based on React, and can make use of Blueprint 3 UI components.

Point of focus of an extension is repository view.
Repository view is essentially a React component that takes no props.
That component is rendered by Paneron, and given some primitives for accessing and changing repository data
(those primitives can be accessed through extension view context—see samples below
and the template extension for an example).

[NOTE]
====
These guidelines are for Paneron 1.0.0-alpha17. Before that version the process was slightly different.
Specifying PANERON_PLUGIN_DIR environment variable is no longer suggested.
====

=== Setup using GitHub as repository host

. Think of an ID for your extension (e.g., my-extension).

. On GitHub, create a new repository using Paneron extension template repository (https://github.com/paneron/extension-template-basic) or registry extension template repository (https://github.com/paneron/extension-template-registry).

. Clone the repository you’ve created and edit package.json to fill in your extension name, description, and author (see placeholders).

. Inside Paneron app data directory, create subdirectory chain 'plugins/@riboseinc/paneron-extension-my-extension'.
+
That is where Paneron will expect your extension built form to reside.

. For testing purposes, obtain Paneron source code (clone https://github.com/paneron/paneron) and build the project locally.

==== Iteration

After you make changes:

. Rebuild your extension from its repository root:
+
[source,sh]
--
$ yarn build
--

. Copy the _contents_ of `dist/` into Paneron’s built extension directory you created during preliminary setup.

. Launch your local build of Paneron using a command like this, from within Paneron repository root:
+
[source,sh]
--
$ env PANERON_DEV_PLUGIN=my-extension yarn dev
--

==== Release

An extension must be released as a separate NPM package, specifying entry as `plugin.js`.
That entry file should call `exposePlugin()` imported from the extension kit,
passing it extension configuration.

NOTE: See the template extension for example packaging.

When ready & tested, release your extension on NPM
by running this command from within `dist/` subdirectory
in your extension repository:

[source,sh]
--
$ npm publish --access public
--

NOTE: `--access public` is only necessary first time you publish the extension. (See link:https://docs.npmjs.com/creating-and-publishing-scoped-public-packages#publishing-scoped-public-packages[NPM CLI docs].)

NOTE: Currently, only extensions released under `@riboseinc` NPM scope are supported.
Plugin name must be prefixed with `paneron-extension-` (e.g., `@riboseinc/paneron-extension-my-extension`).

NOTE: Paneron fetches extension index from extensions.paneron.org; the site must be rebuild after your extension is published. The site rebuilds periodically, but if you want to expedite the process you can trigger the workflow by hand in Actions.

To test your extension after it’s released, run Paneron as a regular user would,
without PANERON_DEV_PLUGIN variable.

=== Rules of Paneron extensions

There are some extra constraints placed upon extension component code, mostly due to limitations
of extension mechanism at this point in time.

. An extension must not have any dependencies specified in package.json.
  Anything you want to import should be provided by Paneron (see below what is).
  (You can use devDependencies, though.)

. An extension cannot call browser window’s native functions.
  If you need `setTimeout()`, use Node’s `setTimeout`.
  Using `Blob` or `addEventListener()` is not possible currently.
+
If this rule is not observed, you may end up getting a confusing blank screen
after opening a repository using your extension and “DevTools was disconnected from the page” in console.

==== Modules you can import

Here are the modules you can import:

* "react"
* "react-window"
* "@emotion/react"
* "@emotion/styled"
* "date-fns"
* "@riboseinc/paneron-extension-kit"
* "@riboseinc/paneron-registry-kit"
* "@blueprintjs/core"
* "@blueprintjs/datetime"
* "@blueprintjs/icons"
* "@blueprintjs/select"
* "electron-log"
* "js-yaml"
* "throttle-debounce"

Again, you must not have anything in your dependencies,
but you may want to add what you use from the above to your _devDependencies_
for TypeScript development convenience.

=== Using Emotion for styling components

Here’s how a simple component can be written using Emotion:

[source,tsx]
--
/** @jsx jsx */

import React, { useContext, useState } from 'react';
import { css, jsx } from '@emotion/react';
import { ExtensionViewContext } from '@riboseinc/paneron-extension-kit/context';

const MyRepositoryView: React.FC<Record<never, never>> = function () {
  const { title } = useContext(ExtensionViewContext);
  const [value, setValue] = useState(null);
  return <div css={css`padding: 1rem;`}>Welcome to repository {title}!</div>;
};
--

[NOTE]
====
If using React fragment shorthand syntax (`<>…</>`),
use `@jsxFrag` pragma:

[source,tsx]
--
/** @jsx jsx */
/** @jsxFrag React.Fragment */

import React, { useContext, useState } from 'react';
import { css, jsx } from '@emotion/react';
import { ExtensionViewContext } from '@riboseinc/paneron-extension-kit/context';

const MyRepositoryView: React.FC<Record<never, never>> = function () {
  const { title } = useContext(ExtensionViewContext);
  const [value, setValue] = useState(null);
  return <>
    <div css={css`padding: 1rem;`}>Welcome to repository {title}!</div>
  </>;
};
--
====
